"""
扩展西班牙语词源学字典 - 批量添加
为 LCDP S3E01 中所有缺失词源学的单词添加条目
"""

NEW_ETYMOLOGY_ENTRIES = {
    # ---- A ----
    "andrés": {"translation": "安德烈斯", "breakdown": [{"part": "Andrés", "origin": "希腊语 Andreas", "meaning": "男人气的/勇敢的"}]},
    "balcanes": {"translation": "巴尔干", "breakdown": [{"part": "Balcan-", "origin": "土耳其语 Balkan", "meaning": "山脉"}, {"part": "-es", "origin": "复数标记", "meaning": "复数后缀"}]},
    "barrios": {"translation": "街区", "breakdown": [{"part": "barr-", "origin": "拉丁语 barra", "meaning": "条/杆 → 街区"}, {"part": "-ios", "origin": "复数标记", "meaning": "复数后缀"}]},
    "berlín": {"translation": "柏林", "breakdown": [{"part": "Berlín", "origin": "西斯拉夫语 berlo", "meaning": "沼泽地（地名）"}]},
    "boludo": {"translation": "傻瓜", "breakdown": [{"part": "bol-", "origin": "拉丁语 bulla", "meaning": "球/气泡"}, {"part": "-udo", "origin": "拉丁语 -ūtus", "meaning": "充满...的"}]},
    "bombazo": {"translation": "猛烈爆炸", "breakdown": [{"part": "bomb-", "origin": "拟声词 bomba", "meaning": "爆炸声"}, {"part": "-azo", "origin": "指大后缀", "meaning": "猛烈打击"}]},
    "bragueta": {"translation": "裤裆", "breakdown": [{"part": "brag-", "origin": "拉丁语 braca", "meaning": "裤子"}, {"part": "-ueta", "origin": "指小后缀", "meaning": "小"}]},
    "busco": {"translation": "我寻找", "breakdown": [{"part": "busc-", "origin": "拉丁语 buscare", "meaning": "寻找"}, {"part": "-o", "origin": "动词后缀", "meaning": "第一人称单数"}]},
    "callejón": {"translation": "小巷", "breakdown": [{"part": "callej-", "origin": "拉丁语 callis", "meaning": "小路"}, {"part": "-ón", "origin": "指大后缀", "meaning": "大"}]},
    "camión": {"translation": "卡车", "breakdown": [{"part": "cam-", "origin": "拉丁语 caminus", "meaning": "路"}, {"part": "-ión", "origin": "指大后缀", "meaning": "大"}]},
    "canal": {"translation": "渠道", "breakdown": [{"part": "can-", "origin": "拉丁语 canalis", "meaning": "管道"}, {"part": "-al", "origin": "拉丁语 -ālem", "meaning": "相关"}]},
    "canto": {"translation": "歌唱", "breakdown": [{"part": "cant-", "origin": "拉丁语 cantus", "meaning": "歌唱"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "capacidad": {"translation": "能力", "breakdown": [{"part": "capac-", "origin": "拉丁语 capax", "meaning": "能容纳的"}, {"part": "-idad", "origin": "拉丁语 -itātem", "meaning": "抽象名词后缀"}]},
    "capilla": {"translation": "小教堂", "breakdown": [{"part": "cap-", "origin": "拉丁语 capa", "meaning": "斗篷"}, {"part": "-illa", "origin": "指小后缀", "meaning": "小"}]},
    "carga": {"translation": "负担", "breakdown": [{"part": "carg-", "origin": "拉丁语 carricare", "meaning": "装载"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "caribe": {"translation": "加勒比", "breakdown": [{"part": "Caribe", "origin": "加勒比语 Karina", "meaning": "人/民族"}]},
    "cariño": {"translation": "关爱", "breakdown": [{"part": "cariñ-", "origin": "拉丁语 carus", "meaning": "亲爱的"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "casablanca": {"translation": "卡萨布兰卡", "breakdown": [{"part": "casa", "origin": "拉丁语 casa", "meaning": "房子"}, {"part": "blanca", "origin": "拉丁语 blancus", "meaning": "白色"}]},
    "casita": {"translation": "小房子", "breakdown": [{"part": "cas-", "origin": "拉丁语 casa", "meaning": "房子"}, {"part": "-ita", "origin": "指小后缀", "meaning": "小"}]},
    "caso": {"translation": "案件", "breakdown": [{"part": "cas-", "origin": "拉丁语 casus", "meaning": "事件"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "celda": {"translation": "牢房", "breakdown": [{"part": "celd-", "origin": "拉丁语 cella", "meaning": "小房间"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "centro": {"translation": "中心", "breakdown": [{"part": "centr-", "origin": "希腊语 kentron", "meaning": "中心点"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "certeza": {"translation": "确定性", "breakdown": [{"part": "cert-", "origin": "拉丁语 certus", "meaning": "确定的"}, {"part": "-eza", "origin": "拉丁语 -itia", "meaning": "性质后缀"}]},
    "champán": {"translation": "香槟", "breakdown": [{"part": "Champán", "origin": "法语 Champagne", "meaning": "香槟地区"}]},
    "chunda": {"translation": "春达", "breakdown": [{"part": "Chunda", "origin": "昵称", "meaning": "人名"}]},
    "cia": {"translation": "公司", "breakdown": [{"part": "Cía.", "origin": "compañía 缩写", "meaning": "公司"}]},
    "cistercienses": {"translation": "西多会", "breakdown": [{"part": "Cisterci-", "origin": "拉丁语 Cistercium", "meaning": "西多"}, {"part": "-ense", "origin": "拉丁语 -ensis", "meaning": "来自...的"}, {"part": "-s", "origin": "复数标记", "meaning": "复数"}]},
    "cita": {"translation": "约会", "breakdown": [{"part": "cit-", "origin": "拉丁语 citare", "meaning": "召唤"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "clase": {"translation": "班级", "breakdown": [{"part": "clas-", "origin": "拉丁语 classis", "meaning": "阶级"}, {"part": "-e", "origin": "名词后缀", "meaning": "名词标记"}]},
    "comando": {"translation": "命令", "breakdown": [{"part": "comand-", "origin": "拉丁语 commandare", "meaning": "委托"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "comida": {"translation": "食物", "breakdown": [{"part": "com-", "origin": "拉丁语 comedere", "meaning": "吃"}, {"part": "-ida", "origin": "过去分词后缀", "meaning": "结果"}]},
    "comprasteis": {"translation": "你们买了", "breakdown": [{"part": "compr-", "origin": "拉丁语 comparare", "meaning": "购买"}, {"part": "-asteis", "origin": "动词后缀", "meaning": "第二人称复数过去时"}]},
    "comunicación": {"translation": "交流", "breakdown": [{"part": "comunic-", "origin": "拉丁语 communicare", "meaning": "分享"}, {"part": "-ación", "origin": "拉丁语 -tiōnem", "meaning": "动作名词后缀"}]},
    "contacten": {"translation": "他们联系", "breakdown": [{"part": "contact-", "origin": "拉丁语 contactus", "meaning": "接触"}, {"part": "-en", "origin": "动词后缀", "meaning": "第三人称复数"}]},
    "contigo": {"translation": "和你", "breakdown": [{"part": "con-", "origin": "拉丁语 cum", "meaning": "和"}, {"part": "-tigo", "origin": "拉丁语 tēcum", "meaning": "和你"}]},
    "continente": {"translation": "大陆", "breakdown": [{"part": "continent-", "origin": "拉丁语 continens", "meaning": "包含的"}, {"part": "-e", "origin": "名词后缀", "meaning": "名词标记"}]},
    "continúe": {"translation": "继续", "breakdown": [{"part": "continu-", "origin": "拉丁语 continuare", "meaning": "连续"}, {"part": "-e", "origin": "动词后缀", "meaning": "虚拟式"}]},
    "corrala": {"translation": "传统公寓", "breakdown": [{"part": "corral-", "origin": "拉丁语 coralium", "meaning": "院子"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "corre": {"translation": "他跑", "breakdown": [{"part": "corr-", "origin": "拉丁语 currere", "meaning": "跑"}, {"part": "-e", "origin": "动词后缀", "meaning": "第三人称单数"}]},
    "corredor": {"translation": "走廊", "breakdown": [{"part": "corred-", "origin": "拉丁语 currere", "meaning": "跑"}, {"part": "-or", "origin": "拉丁语 -tōrem", "meaning": "行为者/地点"}]},
    "criminal": {"translation": "罪犯", "breakdown": [{"part": "crimin-", "origin": "拉丁语 crimen", "meaning": "罪行"}, {"part": "-al", "origin": "拉丁语 -ālem", "meaning": "相关"}]},
    "créanme": {"translation": "相信我", "breakdown": [{"part": "cre-", "origin": "拉丁语 credere", "meaning": "相信"}, {"part": "-an", "origin": "动词后缀", "meaning": "第三人称复数"}, {"part": "-me", "origin": "代词", "meaning": "我"}]},
    "crío": {"translation": "小孩", "breakdown": [{"part": "cri-", "origin": "拉丁语 criare", "meaning": "抚养"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "culo": {"translation": "屁股", "breakdown": [{"part": "cul-", "origin": "拉丁语 culus", "meaning": "臀部"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "culpa": {"translation": "过错", "breakdown": [{"part": "culp-", "origin": "拉丁语 culpa", "meaning": "过错"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "cuánto": {"translation": "多少", "breakdown": [{"part": "cuánt-", "origin": "拉丁语 quantus", "meaning": "多少"}, {"part": "-o", "origin": "疑问后缀", "meaning": "疑问标记"}]},
    "decisión": {"translation": "决定", "breakdown": [{"part": "decis-", "origin": "拉丁语 decidere", "meaning": "决定"}, {"part": "-ión", "origin": "拉丁语 -siōnem", "meaning": "动作名词后缀"}]},
    "declaración": {"translation": "声明", "breakdown": [{"part": "declar-", "origin": "拉丁语 declarare", "meaning": "声明"}, {"part": "-ación", "origin": "拉丁语 -tiōnem", "meaning": "动作名词后缀"}]},
    "denver": {"translation": "丹佛", "breakdown": [{"part": "Denver", "origin": "法语地名", "meaning": "地名"}]},
    "depósito": {"translation": "存款", "breakdown": [{"part": "deposit-", "origin": "拉丁语 depositum", "meaning": "存放物"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "dignidad": {"translation": "尊严", "breakdown": [{"part": "dign-", "origin": "拉丁语 dignus", "meaning": "值得的"}, {"part": "-idad", "origin": "拉丁语 -itātem", "meaning": "抽象名词后缀"}]},
    "dime": {"translation": "告诉我", "breakdown": [{"part": "di-", "origin": "拉丁语 dicere", "meaning": "说"}, {"part": "-me", "origin": "代词", "meaning": "我"}]},
    "elefante": {"translation": "大象", "breakdown": [{"part": "elefant-", "origin": "拉丁语 elephantus", "meaning": "大象"}, {"part": "-e", "origin": "名词后缀", "meaning": "名词标记"}]},
    "embargo": {"translation": "禁运", "breakdown": [{"part": "embarg-", "origin": "拉丁语 imbarricare", "meaning": "阻碍"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "empiezas": {"translation": "你开始", "breakdown": [{"part": "empiez-", "origin": "拉丁语 initium", "meaning": "开始"}, {"part": "-as", "origin": "动词后缀", "meaning": "第二人称单数"}]},
    "enciéndelo": {"translation": "点燃它", "breakdown": [{"part": "enciend-", "origin": "拉丁语 incendere", "meaning": "点燃"}, {"part": "-e", "origin": "动词后缀", "meaning": "命令式"}, {"part": "-lo", "origin": "代词", "meaning": "它"}]},
    "encuentro": {"translation": "相遇", "breakdown": [{"part": "encuentr-", "origin": "拉丁语 invenire", "meaning": "找到"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "error": {"translation": "错误", "breakdown": [{"part": "err-", "origin": "拉丁语 errare", "meaning": "犯错"}, {"part": "-or", "origin": "拉丁语 -ōrem", "meaning": "结果后缀"}]},
    "espalda": {"translation": "背部", "breakdown": [{"part": "espald-", "origin": "拉丁语 spatha", "meaning": "肩胛骨"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "españa": {"translation": "西班牙", "breakdown": [{"part": "España", "origin": "拉丁语 Hispania", "meaning": "西班牙"}]},
    "estaréis": {"translation": "你们将在", "breakdown": [{"part": "estar-", "origin": "拉丁语 stare", "meaning": "在"}, {"part": "-éis", "origin": "动词后缀", "meaning": "第二人称复数将来时"}]},
    "estilo": {"translation": "风格", "breakdown": [{"part": "estil-", "origin": "拉丁语 stilus", "meaning": "笔/风格"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "europa": {"translation": "欧洲", "breakdown": [{"part": "Europa", "origin": "希腊语 Eurōpē", "meaning": "欧洲"}]},
    "europol": {"translation": "欧洲刑警", "breakdown": [{"part": "Euro-", "origin": "Europa", "meaning": "欧洲"}, {"part": "-pol", "origin": "希腊语 polis", "meaning": "警察"}]},
    "euros": {"translation": "欧元", "breakdown": [{"part": "eur-", "origin": "Europa", "meaning": "欧洲"}, {"part": "-os", "origin": "复数标记", "meaning": "复数"}]},
    "explosivo": {"translation": "爆炸性的", "breakdown": [{"part": "explos-", "origin": "拉丁语 explodere", "meaning": "爆炸"}, {"part": "-ivo", "origin": "拉丁语 -īvus", "meaning": "相关"}]},
    "favor": {"translation": "恩惠", "breakdown": [{"part": "fav-", "origin": "拉丁语 favor", "meaning": "支持"}, {"part": "-or", "origin": "拉丁语 -ōrem", "meaning": "抽象名词后缀"}]},
    "felicidad": {"translation": "幸福", "breakdown": [{"part": "felic-", "origin": "拉丁语 felix", "meaning": "幸福的"}, {"part": "-idad", "origin": "拉丁语 -itātem", "meaning": "抽象名词后缀"}]},
    "fiesta": {"translation": "节日", "breakdown": [{"part": "fiest-", "origin": "拉丁语 festa", "meaning": "节日"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "filosofía": {"translation": "哲学", "breakdown": [{"part": "filo-", "origin": "希腊语 philia", "meaning": "爱"}, {"part": "-sof-", "origin": "希腊语 sophia", "meaning": "智慧"}, {"part": "-ía", "origin": "希腊语 -ia", "meaning": "学科"}]},
    "final": {"translation": "结尾", "breakdown": [{"part": "fin-", "origin": "拉丁语 finis", "meaning": "结束"}, {"part": "-al", "origin": "拉丁语 -ālem", "meaning": "相关"}]},
    "forma": {"translation": "形状", "breakdown": [{"part": "form-", "origin": "拉丁语 forma", "meaning": "形状"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "frena": {"translation": "他刹车", "breakdown": [{"part": "fren-", "origin": "拉丁语 frenum", "meaning": "缰绳"}, {"part": "-a", "origin": "动词后缀", "meaning": "第三人称单数"}]},
    "frente": {"translation": "额头", "breakdown": [{"part": "frent-", "origin": "拉丁语 frons", "meaning": "额头"}, {"part": "-e", "origin": "名词后缀", "meaning": "名词标记"}]},
    "fábrica": {"translation": "工厂", "breakdown": [{"part": "fábric-", "origin": "拉丁语 fabrica", "meaning": "作坊"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "gloria": {"translation": "荣耀", "breakdown": [{"part": "glor-", "origin": "拉丁语 gloria", "meaning": "荣耀"}, {"part": "-ia", "origin": "拉丁语 -ia", "meaning": "状态"}]},
    "gobierno": {"translation": "政府", "breakdown": [{"part": "gobiern-", "origin": "拉丁语 gubernare", "meaning": "统治"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "gracia": {"translation": "恩典", "breakdown": [{"part": "graci-", "origin": "拉丁语 gratia", "meaning": "恩典"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "gracias": {"translation": "谢谢", "breakdown": [{"part": "graci-", "origin": "拉丁语 gratia", "meaning": "感谢"}, {"part": "-as", "origin": "复数标记", "meaning": "复数"}]},
    "gregoriano": {"translation": "格里高利的", "breakdown": [{"part": "Gregori-", "origin": "拉丁语 Gregorius", "meaning": "格里高利"}, {"part": "-ano", "origin": "拉丁语 -ānus", "meaning": "属于...的"}]},
    "guantánamo": {"translation": "关塔那摩", "breakdown": [{"part": "Guantánamo", "origin": "泰诺语", "meaning": "地名"}]},
    "guarda": {"translation": "守卫", "breakdown": [{"part": "guard-", "origin": "日耳曼语 wardon", "meaning": "守卫"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "guindo": {"translation": "酸樱桃", "breakdown": [{"part": "guind-", "origin": "拉丁语 cerasus", "meaning": "樱桃"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "guna": {"translation": "古纳", "breakdown": [{"part": "Guna", "origin": "地名", "meaning": "专有名词"}]},
    "hacedlo": {"translation": "做吧", "breakdown": [{"part": "hac-", "origin": "拉丁语 facere", "meaning": "做"}, {"part": "-ed", "origin": "动词后缀", "meaning": "第二人称复数命令式"}, {"part": "-lo", "origin": "代词", "meaning": "它"}]},
    "helsinki": {"translation": "赫尔辛基", "breakdown": [{"part": "Helsinki", "origin": "芬兰语", "meaning": "地名"}]},
    "hermanito": {"translation": "弟弟", "breakdown": [{"part": "herman-", "origin": "拉丁语 germanus", "meaning": "兄弟"}, {"part": "-ito", "origin": "指小后缀", "meaning": "小"}]},
    "hija": {"translation": "女儿", "breakdown": [{"part": "hij-", "origin": "拉丁语 filia", "meaning": "女儿"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "hijaputa": {"translation": "婊子养的", "breakdown": [{"part": "hija", "origin": "拉丁语 filia", "meaning": "女儿"}, {"part": "puta", "origin": "拉丁语 puta", "meaning": "妓女"}]},
    "hood": {"translation": "兜帽", "breakdown": [{"part": "hood", "origin": "英语 hood", "meaning": "兜帽"}]},
    "hostia": {"translation": "圣饼", "breakdown": [{"part": "host-", "origin": "拉丁语 hostia", "meaning": "牺牲"}, {"part": "-ia", "origin": "拉丁语 -ia", "meaning": "名词后缀"}]},
    "hotel": {"translation": "酒店", "breakdown": [{"part": "hot-", "origin": "法语 hôtel", "meaning": "酒店"}, {"part": "-el", "origin": "法语后缀", "meaning": "场所"}]},
    "héroe": {"translation": "英雄", "breakdown": [{"part": "héroe", "origin": "希腊语 hērōs", "meaning": "英雄"}]},
    "idiota": {"translation": "白痴", "breakdown": [{"part": "idiot-", "origin": "希腊语 idiōtēs", "meaning": "普通人"}, {"part": "-a", "origin": "名词后缀", "meaning": "名词标记"}]},
    "inercia": {"translation": "惯性", "breakdown": [{"part": "inerc-", "origin": "拉丁语 inertia", "meaning": "无活性"}, {"part": "-ia", "origin": "拉丁语 -ia", "meaning": "状态"}]},
    "información": {"translation": "信息", "breakdown": [{"part": "inform-", "origin": "拉丁语 informare", "meaning": "通知"}, {"part": "-ación", "origin": "拉丁语 -tiōnem", "meaning": "动作名词后缀"}]},
    "ingeniería": {"translation": "工程", "breakdown": [{"part": "ingeni-", "origin": "拉丁语 ingenium", "meaning": "天赋"}, {"part": "-ería", "origin": "拉丁语 -aria", "meaning": "行业"}]},
    "inteligencia": {"translation": "智力", "breakdown": [{"part": "intelig-", "origin": "拉丁语 intellegere", "meaning": "理解"}, {"part": "-encia", "origin": "拉丁语 -entia", "meaning": "状态后缀"}]},
    "intención": {"translation": "意图", "breakdown": [{"part": "intenc-", "origin": "拉丁语 intentio", "meaning": "意图"}, {"part": "-ión", "origin": "拉丁语 -tiōnem", "meaning": "动作名词后缀"}]},
    "interpol": {"translation": "国际刑警", "breakdown": [{"part": "Inter-", "origin": "拉丁语 inter", "meaning": "国际"}, {"part": "-pol", "origin": "希腊语 polis", "meaning": "警察"}]},
    "isla": {"translation": "岛", "breakdown": [{"part": "isl-", "origin": "拉丁语 insula", "meaning": "岛"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "italia": {"translation": "意大利", "breakdown": [{"part": "Italia", "origin": "拉丁语 Italia", "meaning": "意大利"}]},
    "jarana": {"translation": "狂欢", "breakdown": [{"part": "jar-", "origin": "阿拉伯语", "meaning": "喧闹"}, {"part": "-ana", "origin": "名词后缀", "meaning": "行为"}]},
    "jardín": {"translation": "花园", "breakdown": [{"part": "jard-", "origin": "法语 jardin", "meaning": "花园"}, {"part": "-ín", "origin": "指小后缀", "meaning": "小"}]},
    "jefe": {"translation": "老板", "breakdown": [{"part": "jef-", "origin": "法语 chef", "meaning": "首领"}, {"part": "-e", "origin": "名词后缀", "meaning": "名词标记"}]},
    "juez": {"translation": "法官", "breakdown": [{"part": "juez", "origin": "拉丁语 iudex", "meaning": "法官"}]},
    "jurisdicción": {"translation": "管辖权", "breakdown": [{"part": "jurisdic-", "origin": "拉丁语 iurisdictio", "meaning": "法律宣告"}, {"part": "-ción", "origin": "拉丁语 -tiōnem", "meaning": "动作名词后缀"}]},
    "liarla": {"translation": "搞砸", "breakdown": [{"part": "li-", "origin": "拉丁语 ligare", "meaning": "绑"}, {"part": "-arla", "origin": "动词+代词", "meaning": "它"}]},
    "libio": {"translation": "利比亚人", "breakdown": [{"part": "Lib-", "origin": "拉丁语 Libya", "meaning": "利比亚"}, {"part": "-io", "origin": "拉丁语 -ius", "meaning": "属于...的"}]},
    "loca": {"translation": "疯女人", "breakdown": [{"part": "loc-", "origin": "拉丁语 locus", "meaning": "疯狂"}, {"part": "-a", "origin": "阴性后缀", "meaning": "阴性标记"}]},
    "localización": {"translation": "定位", "breakdown": [{"part": "localiz-", "origin": "拉丁语 locus", "meaning": "地方"}, {"part": "-ación", "origin": "拉丁语 -tiōnem", "meaning": "动作名词后缀"}]},
    "lugar": {"translation": "地方", "breakdown": [{"part": "lug-", "origin": "拉丁语 locus", "meaning": "地方"}, {"part": "-ar", "origin": "拉丁语 -ārem", "meaning": "相关"}]},
    "lujo": {"translation": "奢侈", "breakdown": [{"part": "luj-", "origin": "拉丁语 luxus", "meaning": "奢侈"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "m16": {"translation": "M16步枪", "breakdown": [{"part": "M16", "origin": "军事编号", "meaning": "型号"}]},
    "madrid": {"translation": "马德里", "breakdown": [{"part": "Madrid", "origin": "阿拉伯语 Majrit", "meaning": "水源丰富之地"}]},
    "manera": {"translation": "方式", "breakdown": [{"part": "maner-", "origin": "拉丁语 manus", "meaning": "手"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "manos": {"translation": "手", "breakdown": [{"part": "man-", "origin": "拉丁语 manus", "meaning": "手"}, {"part": "-os", "origin": "复数标记", "meaning": "复数"}]},
    "manzana": {"translation": "苹果", "breakdown": [{"part": "manzan-", "origin": "拉丁语 matiana", "meaning": "苹果"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "maravilla": {"translation": "奇迹", "breakdown": [{"part": "marav-", "origin": "拉丁语 mirabilia", "meaning": "奇迹"}, {"part": "-illa", "origin": "指小后缀", "meaning": "小"}]},
    "mañana": {"translation": "明天", "breakdown": [{"part": "mañ-", "origin": "拉丁语 mane", "meaning": "早晨"}, {"part": "-ana", "origin": "名词后缀", "meaning": "时间"}]},
    "mente": {"translation": "思想", "breakdown": [{"part": "ment-", "origin": "拉丁语 mens", "meaning": "心智"}, {"part": "-e", "origin": "名词后缀", "meaning": "名词标记"}]},
    "mercado": {"translation": "市场", "breakdown": [{"part": "mercad-", "origin": "拉丁语 mercatus", "meaning": "交易"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "mierda": {"translation": "屎", "breakdown": [{"part": "mierd-", "origin": "拉丁语 merda", "meaning": "粪便"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "mindanao": {"translation": "棉兰老岛", "breakdown": [{"part": "Mindanao", "origin": "菲律宾语", "meaning": "地名"}]},
    "minuto": {"translation": "分钟", "breakdown": [{"part": "minut-", "origin": "拉丁语 minutus", "meaning": "微小的"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "momento": {"translation": "时刻", "breakdown": [{"part": "moment-", "origin": "拉丁语 momentum", "meaning": "运动"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "monasterio": {"translation": "修道院", "breakdown": [{"part": "monaster-", "origin": "希腊语 monastērion", "meaning": "修道院"}, {"part": "-io", "origin": "拉丁语 -ium", "meaning": "地点"}]},
    "moneda": {"translation": "货币", "breakdown": [{"part": "mon-", "origin": "拉丁语 moneta", "meaning": "铸币厂"}, {"part": "-eda", "origin": "名词后缀", "meaning": "名词标记"}]},
    "monstruo": {"translation": "怪物", "breakdown": [{"part": "monstru-", "origin": "拉丁语 monstrum", "meaning": "怪物"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "mujer": {"translation": "女人", "breakdown": [{"part": "muj-", "origin": "拉丁语 mulier", "meaning": "女人"}, {"part": "-er", "origin": "名词后缀", "meaning": "名词标记"}]},
    "nacional": {"translation": "国家的", "breakdown": [{"part": "nacion-", "origin": "拉丁语 natio", "meaning": "民族"}, {"part": "-al", "origin": "拉丁语 -ālem", "meaning": "相关"}]},
    "nairobi": {"translation": "内罗毕", "breakdown": [{"part": "Nairobi", "origin": "马赛语", "meaning": "冷水之地"}]},
    "necesita": {"translation": "他需要", "breakdown": [{"part": "necesit-", "origin": "拉丁语 necesse", "meaning": "必要的"}, {"part": "-a", "origin": "动词后缀", "meaning": "第三人称单数"}]},
    "negativo": {"translation": "否定的", "breakdown": [{"part": "negat-", "origin": "拉丁语 negare", "meaning": "否认"}, {"part": "-ivo", "origin": "拉丁语 -īvus", "meaning": "相关"}]},
    "niña": {"translation": "女孩", "breakdown": [{"part": "niñ-", "origin": "拉丁语 ninnus", "meaning": "小孩"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "阴性标记"}]},
    "niño": {"translation": "男孩", "breakdown": [{"part": "niñ-", "origin": "拉丁语 ninnus", "meaning": "小孩"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "阳性标记"}]},
    "norma": {"translation": "规范", "breakdown": [{"part": "norm-", "origin": "拉丁语 norma", "meaning": "规则"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "noticia": {"translation": "新闻", "breakdown": [{"part": "notic-", "origin": "拉丁语 notitia", "meaning": "消息"}, {"part": "-ia", "origin": "拉丁语 -ia", "meaning": "状态"}]},
    "número": {"translation": "数字", "breakdown": [{"part": "númer-", "origin": "拉丁语 numerus", "meaning": "数字"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "objetivo": {"translation": "目标", "breakdown": [{"part": "objet-", "origin": "拉丁语 objectum", "meaning": "对象"}, {"part": "-ivo", "origin": "拉丁语 -īvus", "meaning": "相关"}]},
    "obra": {"translation": "作品", "breakdown": [{"part": "obr-", "origin": "拉丁语 opera", "meaning": "工作"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "opio": {"translation": "鸦片", "breakdown": [{"part": "opi-", "origin": "希腊语 opion", "meaning": "鸦片"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "panamá": {"translation": "巴拿马", "breakdown": [{"part": "Panamá", "origin": "印第安语", "meaning": "鱼多之地"}]},
    "paraíso": {"translation": "天堂", "breakdown": [{"part": "paraís-", "origin": "希腊语 paradeisos", "meaning": "花园"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "pareja": {"translation": "伴侣", "breakdown": [{"part": "parej-", "origin": "拉丁语 paria", "meaning": "一对"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "patio": {"translation": "院子", "breakdown": [{"part": "pat-", "origin": "拉丁语 patere", "meaning": "展开"}, {"part": "-io", "origin": "拉丁语 -ium", "meaning": "地点"}]},
    "patrulleras": {"translation": "巡逻艇", "breakdown": [{"part": "patrull-", "origin": "法语 patrouille", "meaning": "巡逻"}, {"part": "-era", "origin": "阴性名词后缀", "meaning": "工具"}, {"part": "-s", "origin": "复数标记", "meaning": "复数"}]},
    "país": {"translation": "国家", "breakdown": [{"part": "país", "origin": "拉丁语 pagensis", "meaning": "地区"}]},
    "pedro": {"translation": "佩德罗", "breakdown": [{"part": "Pedro", "origin": "希腊语 Petros", "meaning": "石头"}]},
    "peligro": {"translation": "危险", "breakdown": [{"part": "pelig-", "origin": "拉丁语 periculum", "meaning": "危险"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "película": {"translation": "电影", "breakdown": [{"part": "películ-", "origin": "拉丁语 pellicula", "meaning": "薄膜"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "perdí": {"translation": "我输了", "breakdown": [{"part": "perd-", "origin": "拉丁语 perdere", "meaning": "失去"}, {"part": "-í", "origin": "动词后缀", "meaning": "第一人称过去时"}]},
    "pesar": {"translation": "遗憾", "breakdown": [{"part": "pes-", "origin": "拉丁语 pensare", "meaning": "称重"}, {"part": "-ar", "origin": "动词后缀", "meaning": "不定式"}]},
    "petrolero": {"translation": "油轮", "breakdown": [{"part": "petrol-", "origin": "拉丁语 petra+oleum", "meaning": "石油"}, {"part": "-ero", "origin": "拉丁语 -ārius", "meaning": "相关"}]},
    "piso": {"translation": "地板", "breakdown": [{"part": "pis-", "origin": "拉丁语 pinsare", "meaning": "踩踏"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "plan": {"translation": "计划", "breakdown": [{"part": "plan", "origin": "拉丁语 planus", "meaning": "平坦/计划"}]},
    "policía": {"translation": "警察", "breakdown": [{"part": "polic-", "origin": "希腊语 polis", "meaning": "城市"}, {"part": "-ía", "origin": "希腊语 -ia", "meaning": "管理"}]},
    "posición": {"translation": "位置", "breakdown": [{"part": "posic-", "origin": "拉丁语 positio", "meaning": "放置"}, {"part": "-ón", "origin": "拉丁语 -tiōnem", "meaning": "动作名词后缀"}]},
    "prieto": {"translation": "黑暗的", "breakdown": [{"part": "pri-", "origin": "拉丁语 pressus", "meaning": "紧的"}, {"part": "-eto", "origin": "形容词后缀", "meaning": "性质"}]},
    "problema": {"translation": "问题", "breakdown": [{"part": "problem-", "origin": "希腊语 problēma", "meaning": "问题"}, {"part": "-a", "origin": "希腊语 -a", "meaning": "名词标记"}]},
    "profesor": {"translation": "教授", "breakdown": [{"part": "profes-", "origin": "拉丁语 profiteri", "meaning": "声明"}, {"part": "-or", "origin": "拉丁语 -tōrem", "meaning": "行为者"}]},
    "puerto": {"translation": "港口", "breakdown": [{"part": "puert-", "origin": "拉丁语 portus", "meaning": "港口"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "pulso": {"translation": "脉搏", "breakdown": [{"part": "puls-", "origin": "拉丁语 pulsus", "meaning": "跳动"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "punta": {"translation": "尖端", "breakdown": [{"part": "punt-", "origin": "拉丁语 puncta", "meaning": "尖"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "punto": {"translation": "点", "breakdown": [{"part": "punt-", "origin": "拉丁语 punctum", "meaning": "点"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "puta": {"translation": "妓女", "breakdown": [{"part": "put-", "origin": "拉丁语 puta", "meaning": "妓女"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "阴性标记"}]},
    "puto": {"translation": "混蛋", "breakdown": [{"part": "put-", "origin": "拉丁语 putus", "meaning": "男孩"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "阳性标记"}]},
    "puñetero": {"translation": "该死的", "breakdown": [{"part": "puñet-", "origin": "拉丁语 pugnus", "meaning": "拳头"}, {"part": "-ero", "origin": "拉丁语 -ārius", "meaning": "相关"}]},
    "recompensa": {"translation": "奖励", "breakdown": [{"part": "recompens-", "origin": "拉丁语 recompensare", "meaning": "补偿"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "reforma": {"translation": "改革", "breakdown": [{"part": "reform-", "origin": "拉丁语 reformare", "meaning": "重塑"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "rehén": {"translation": "人质", "breakdown": [{"part": "rehén", "origin": "阿拉伯语 rahan", "meaning": "抵押"}]},
    "reserva": {"translation": "储备", "breakdown": [{"part": "reserv-", "origin": "拉丁语 reservare", "meaning": "保留"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "resistencia": {"translation": "抵抗", "breakdown": [{"part": "resist-", "origin": "拉丁语 resistere", "meaning": "抵抗"}, {"part": "-encia", "origin": "拉丁语 -entia", "meaning": "状态后缀"}]},
    "responsable": {"translation": "负责的", "breakdown": [{"part": "respons-", "origin": "拉丁语 respondere", "meaning": "回答"}, {"part": "-able", "origin": "拉丁语 -abilis", "meaning": "能够...的"}]},
    "retiro": {"translation": "退休", "breakdown": [{"part": "retir-", "origin": "拉丁语 retrahere", "meaning": "拉回"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "retraso": {"translation": "延迟", "breakdown": [{"part": "retras-", "origin": "拉丁语 retrahere", "meaning": "延迟"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "rito": {"translation": "仪式", "breakdown": [{"part": "rit-", "origin": "拉丁语 ritus", "meaning": "仪式"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "robin": {"translation": "罗宾", "breakdown": [{"part": "Robin", "origin": "日耳曼语 Hrodberht", "meaning": "名声+明亮"}]},
    "ruido": {"translation": "噪音", "breakdown": [{"part": "ruid-", "origin": "拉丁语 rugitus", "meaning": "吼叫"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "sabes": {"translation": "你知道", "breakdown": [{"part": "sab-", "origin": "拉丁语 sapere", "meaning": "知道"}, {"part": "-es", "origin": "动词后缀", "meaning": "第二人称单数"}]},
    "sacaste": {"translation": "你拿出", "breakdown": [{"part": "sac-", "origin": "拉丁语 sacculare", "meaning": "拿出"}, {"part": "-aste", "origin": "动词后缀", "meaning": "第二人称过去时"}]},
    "secreto": {"translation": "秘密", "breakdown": [{"part": "secret-", "origin": "拉丁语 secretus", "meaning": "秘密的"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "segundo": {"translation": "秒", "breakdown": [{"part": "segund-", "origin": "拉丁语 secundus", "meaning": "第二"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "seguridad": {"translation": "安全", "breakdown": [{"part": "segur-", "origin": "拉丁语 securus", "meaning": "安全的"}, {"part": "-idad", "origin": "拉丁语 -itātem", "meaning": "抽象名词后缀"}]},
    "sergio": {"translation": "塞尔吉奥", "breakdown": [{"part": "Sergio", "origin": "拉丁语 Sergius", "meaning": "罗马氏族名"}]},
    "setenta": {"translation": "七十", "breakdown": [{"part": "setent-", "origin": "拉丁语 septuaginta", "meaning": "七十"}, {"part": "-a", "origin": "数词后缀", "meaning": "数词"}]},
    "siglo": {"translation": "世纪", "breakdown": [{"part": "sigl-", "origin": "拉丁语 saeculum", "meaning": "时代"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "silencio": {"translation": "沉默", "breakdown": [{"part": "silenc-", "origin": "拉丁语 silentium", "meaning": "沉默"}, {"part": "-io", "origin": "拉丁语 -ium", "meaning": "状态"}]},
    "simpáticos": {"translation": "友好的", "breakdown": [{"part": "simpát-", "origin": "希腊语 sympatheia", "meaning": "同情"}, {"part": "-ico", "origin": "希腊语 -ikos", "meaning": "相关"}, {"part": "-s", "origin": "复数标记", "meaning": "复数"}]},
    "sistema": {"translation": "系统", "breakdown": [{"part": "sistem-", "origin": "希腊语 systēma", "meaning": "系统"}, {"part": "-a", "origin": "希腊语 -a", "meaning": "名词标记"}]},
    "solo": {"translation": "独自", "breakdown": [{"part": "sol-", "origin": "拉丁语 solus", "meaning": "单独的"}, {"part": "-o", "origin": "形容词后缀", "meaning": "阳性"}]},
    "solomillo": {"translation": "沙朗牛排", "breakdown": [{"part": "solo-", "origin": "拉丁语 solus", "meaning": "单独"}, {"part": "millo", "origin": "拉丁语 milium", "meaning": "小米"}]},
    "solución": {"translation": "解决方案", "breakdown": [{"part": "soluc-", "origin": "拉丁语 solutio", "meaning": "解开"}, {"part": "-ión", "origin": "拉丁语 -tiōnem", "meaning": "动作名词后缀"}]},
    "sputnik": {"translation": "人造卫星", "breakdown": [{"part": "Sputnik", "origin": "俄语 sputnik", "meaning": "旅伴"}]},
    "tailandia": {"translation": "泰国", "breakdown": [{"part": "Tailand-", "origin": "泰语 Thai", "meaning": "自由人"}, {"part": "-ia", "origin": "拉丁语 -ia", "meaning": "地名"}]},
    "tal": {"translation": "这样的", "breakdown": [{"part": "tal", "origin": "拉丁语 talis", "meaning": "这样的"}]},
    "tardaste": {"translation": "你花了时间", "breakdown": [{"part": "tard-", "origin": "拉丁语 tardare", "meaning": "延迟"}, {"part": "-aste", "origin": "动词后缀", "meaning": "第二人称过去时"}]},
    "tatiana": {"translation": "塔蒂亚娜", "breakdown": [{"part": "Tatiana", "origin": "拉丁语 Tatianus", "meaning": "罗马氏族名"}]},
    "techo": {"translation": "屋顶", "breakdown": [{"part": "tech-", "origin": "拉丁语 tectum", "meaning": "覆盖物"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "teléfono": {"translation": "电话", "breakdown": [{"part": "tel-", "origin": "希腊语 tēle", "meaning": "远"}, {"part": "-éfono", "origin": "希腊语 phōnē", "meaning": "声音"}]},
    "templo": {"translation": "寺庙", "breakdown": [{"part": "templ-", "origin": "拉丁语 templum", "meaning": "神圣场所"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "terrorista": {"translation": "恐怖分子", "breakdown": [{"part": "terror-", "origin": "拉丁语 terror", "meaning": "恐惧"}, {"part": "-ista", "origin": "希腊语 -istēs", "meaning": "从业者"}]},
    "todopoderoso": {"translation": "全能的", "breakdown": [{"part": "todo", "origin": "拉丁语 totus", "meaning": "全部"}, {"part": "poderoso", "origin": "拉丁语 poterosus", "meaning": "强大的"}]},
    "tokio": {"translation": "东京", "breakdown": [{"part": "Tokio", "origin": "日语 Tōkyō", "meaning": "东方首都"}]},
    "tranquilo": {"translation": "平静的", "breakdown": [{"part": "tranquil-", "origin": "拉丁语 tranquillus", "meaning": "平静的"}, {"part": "-o", "origin": "形容词后缀", "meaning": "阳性"}]},
    "transportador": {"translation": "运输者", "breakdown": [{"part": "transport-", "origin": "拉丁语 transportare", "meaning": "运输"}, {"part": "-ador", "origin": "拉丁语 -ātor", "meaning": "行为者"}]},
    "tratado": {"translation": "条约", "breakdown": [{"part": "trat-", "origin": "拉丁语 tractare", "meaning": "处理"}, {"part": "-ado", "origin": "过去分词后缀", "meaning": "结果"}]},
    "tu": {"translation": "你的", "breakdown": [{"part": "tu", "origin": "拉丁语 tuus", "meaning": "你的"}]},
    "té": {"translation": "茶", "breakdown": [{"part": "té", "origin": "汉语 chá/tê", "meaning": "茶"}]},
    "tírese": {"translation": "扔自己", "breakdown": [{"part": "tir-", "origin": "拉丁语 tirare", "meaning": "拉"}, {"part": "-ese", "origin": "动词+代词", "meaning": "自己"}]},
    "túnel": {"translation": "隧道", "breakdown": [{"part": "túnel", "origin": "法语 tunnel", "meaning": "隧道"}]},
    "urgencia": {"translation": "紧急", "breakdown": [{"part": "urg-", "origin": "拉丁语 urgere", "meaning": "催促"}, {"part": "-encia", "origin": "拉丁语 -entia", "meaning": "状态"}]},
    "valor": {"translation": "价值", "breakdown": [{"part": "val-", "origin": "拉丁语 valere", "meaning": "强壮/有价值"}, {"part": "-or", "origin": "拉丁语 -ōrem", "meaning": "抽象名词后缀"}]},
    "vaya": {"translation": "走吧/哎呦", "breakdown": [{"part": "vay-", "origin": "拉丁语 vadere", "meaning": "走"}, {"part": "-a", "origin": "动词后缀", "meaning": "虚拟式"}]},
    "ve": {"translation": "他看/去", "breakdown": [{"part": "ve", "origin": "拉丁语 videre/ire", "meaning": "看/去"}]},
    "veces": {"translation": "次", "breakdown": [{"part": "vec-", "origin": "拉丁语 vicis", "meaning": "次/回"}, {"part": "-es", "origin": "复数标记", "meaning": "复数"}]},
    "vendedor": {"translation": "卖方", "breakdown": [{"part": "vended-", "origin": "拉丁语 vendere", "meaning": "卖"}, {"part": "-or", "origin": "拉丁语 -tōrem", "meaning": "行为者"}]},
    "venga": {"translation": "来/好吧", "breakdown": [{"part": "veng-", "origin": "拉丁语 venire", "meaning": "来"}, {"part": "-a", "origin": "动词后缀", "meaning": "虚拟式"}]},
    "verte": {"translation": "看见你", "breakdown": [{"part": "ver-", "origin": "拉丁语 videre", "meaning": "看"}, {"part": "-te", "origin": "代词", "meaning": "你"}]},
    "vez": {"translation": "次", "breakdown": [{"part": "vez", "origin": "拉丁语 vicis", "meaning": "次/回"}]},
    "viajante": {"translation": "旅行者", "breakdown": [{"part": "viaj-", "origin": "拉丁语 viaticum", "meaning": "旅行"}, {"part": "-ante", "origin": "拉丁语 -antem", "meaning": "行为者"}]},
    "viaje": {"translation": "旅行", "breakdown": [{"part": "viaj-", "origin": "拉丁语 viaticum", "meaning": "旅行"}, {"part": "-e", "origin": "名词后缀", "meaning": "名词标记"}]},
    "voto": {"translation": "投票/誓言", "breakdown": [{"part": "vot-", "origin": "拉丁语 votum", "meaning": "誓言"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "zorro": {"translation": "狐狸", "breakdown": [{"part": "zorr-", "origin": "拉丁语 vulpes", "meaning": "狐狸（变体）"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
    "águila": {"translation": "鹰", "breakdown": [{"part": "águil-", "origin": "拉丁语 aquila", "meaning": "鹰"}, {"part": "-a", "origin": "阴性名词后缀", "meaning": "名词标记"}]},
    "ángel": {"translation": "天使", "breakdown": [{"part": "ángel", "origin": "希腊语 angelos", "meaning": "信使"}]},
    "ídolo": {"translation": "偶像", "breakdown": [{"part": "ídol-", "origin": "希腊语 eidōlon", "meaning": "形象/偶像"}, {"part": "-o", "origin": "阳性名词后缀", "meaning": "名词标记"}]},
}
